// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_xmas_gift = "CgkI48Ok5awcEAIQEA"; // <GPGSID>
        public const string achievement_defeat_xmas_snowman = "CgkI48Ok5awcEAIQCg"; // <GPGSID>
        public const string leaderboard_xmas_santa = "CgkI48Ok5awcEAIQFQ"; // <GPGSID>
        public const string leaderboard_xmas_candy = "CgkI48Ok5awcEAIQDw"; // <GPGSID>
        public const string achievement_defeat_xmas_log = "CgkI48Ok5awcEAIQCQ"; // <GPGSID>
        public const string leaderboard_xmas_bell = "CgkI48Ok5awcEAIQDQ"; // <GPGSID>
        public const string achievement_defeat_xmas_tree = "CgkI48Ok5awcEAIQCA"; // <GPGSID>
        public const string leaderboard_xmas_snowman = "CgkI48Ok5awcEAIQEw"; // <GPGSID>
        public const string leaderboard_xmas_ball = "CgkI48Ok5awcEAIQAQ"; // <GPGSID>
        public const string leaderboard_xmas_reindeer = "CgkI48Ok5awcEAIQFA"; // <GPGSID>
        public const string leaderboard_xmas_snowflake = "CgkI48Ok5awcEAIQDg"; // <GPGSID>
        public const string achievement_defeat_xmas_ball = "CgkI48Ok5awcEAIQAg"; // <GPGSID>
        public const string achievement_defeat_xmas_santa = "CgkI48Ok5awcEAIQDA"; // <GPGSID>
        public const string achievement_defeat_xmas_reindeer = "CgkI48Ok5awcEAIQCw"; // <GPGSID>
        public const string leaderboard_xmas_tree = "CgkI48Ok5awcEAIQEQ"; // <GPGSID>
        public const string achievement_defeat_xmas_gift = "CgkI48Ok5awcEAIQBw"; // <GPGSID>
        public const string achievement_defeat_xmas_snowflake = "CgkI48Ok5awcEAIQBQ"; // <GPGSID>
        public const string achievement_defeat_xmas_candy = "CgkI48Ok5awcEAIQBg"; // <GPGSID>
        public const string achievement_defeat_xmas_bell = "CgkI48Ok5awcEAIQBA"; // <GPGSID>
        public const string leaderboard_xmas_log = "CgkI48Ok5awcEAIQEg"; // <GPGSID>

}

